version: "3.8"

services:
  db_service:
    image: mysql:8.0
    container_name: db_tekserd4
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tekser_net

  app_service:
    build: ./app
    container_name: app_tekserd4
    restart: always
    expose:
      - "3000"
    environment:
      DB_HOST: db_service
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db_service
    networks:
      - tekser_net

  nginx_service:
    image: nginx:alpine
    container_name: nginx_tekserd4
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_service
    networks:
      - tekser_net

volumes:
  db_data:

networks:
  tekser_net:
    driver: bridge
